name: Build & Test Routy

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run core tests
      run: swift test -v
    - name: Run UIKit tests
      shell: bash
      run: |
        device_id="$(xcrun simctl list devices available --json | jq -r '[.devices[][] | select(.name | startswith("iPhone"))][0].udid')"
        test -n "$device_id"
        xcodebuild -scheme Routy-Package -destination "platform=iOS Simulator,id=$device_id" test
